server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sport_venue?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Aa123456

  redis:
    host: localhost
    port: 6379

  cloud:
    consul:
      host: localhost
      port: 8500 