spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/.well-known/jwks.json

server:
  port: 8081

# JWT配置
jwt:
  secret: sport-venue-secret-key-2024
  expiration: 86400000 # 24小时

# 用户服务特有配置
user:
  default-role: USER
  password-encoder: bcrypt

---
spring:
  config:
    activate:
      on-profile: dev