spring:
  application:
    name: venue-service

server:
  port: 8082

# 场馆服务特有配置
venue:
  websocket:
    endpoint: /ws/occupancy
    allowed-origins: "*"
  occupancy:
    update-interval: 5000  # 5秒更新一次占用率
    cache-ttl: 300  # 5分钟缓存

---
spring:
  config:
    activate:
      on-profile: dev 