version: '3.8'

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass sportvenue@2024

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: sport_venue
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

volumes:
  redis-data:
  mysql-data: