server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo 